// <auto-generated />
using Inquiry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inquiry.Migrations
{
    [DbContext(typeof(InquiryContext))]
    [Migration("20230727124444_initial_inquiry")]
    partial class initial_inquiry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_CDMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_cdmast");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_CDMEMO", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_cdmemo");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_CFMAST", b =>
                {
                    b.Property<string>("Agama")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AGAMA");

                    b.Property<string>("AlamatId1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ALAMAT_ID_1");

                    b.Property<string>("BranchNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRANCH_NO");

                    b.Property<string>("CifNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("FederalWhCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FEDERAL_WH_CODE");

                    b.Property<string>("JenisKartuIdentitas")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JENIS_KARTU_IDENTITAS");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JENIS_KELAMIN");

                    b.Property<string>("KecamatanId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KECAMATAN_ID");

                    b.Property<string>("KelurahanId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KELURAHAN_ID");

                    b.Property<string>("Kewarganegaraan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KEWARGANEGARAAN");

                    b.Property<string>("KotaId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KOTA_ID");

                    b.Property<string>("NamaCetakan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("NAMA_CETAKAN");

                    b.Property<string>("NamaLengkap")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAMA_LENGKAP");

                    b.Property<string>("NamaSesuaiId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAMA_SESUAI_ID");

                    b.Property<string>("Negara")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NEGARA");

                    b.Property<string>("NoHp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NO_HP");

                    b.Property<string>("NoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NO_ID");

                    b.Property<string>("Npwp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NPWP");

                    b.Property<string>("PropinsiId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PROPINSI_ID");

                    b.Property<string>("StatusPerkawinan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATUS_PERKAWINAN");

                    b.Property<string>("TanggalLahir")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TANGGAL_LAHIR");

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TEMPAT_LAHIR");

                    b.ToTable("abcs_m_cfmast");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_DDMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_ddmast");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_DDMEMO", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_ddmemo");
                });
#pragma warning restore 612, 618
        }
    }
}
