// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cif_inquiry.Data;

#nullable disable

namespace cif_inquiry.Migrations
{
    [DbContext(typeof(CifInquiryContext))]
    partial class CifInquiryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_CFMAST", b =>
                {
                    b.Property<string>("Agama")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AGAMA");

                    b.Property<string>("AlamatId1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ALAMAT_ID_1");

                    b.Property<string>("BranchNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRANCH_NO");

                    b.Property<string>("CifNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("FederalWhCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FEDERAL_WH_CODE");

                    b.Property<string>("JenisKartuIdentitas")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JENIS_KARTU_IDENTITAS");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JENIS_KELAMIN");

                    b.Property<string>("KecamatanId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KECAMATAN_ID");

                    b.Property<string>("KelurahanId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KELURAHAN_ID");

                    b.Property<string>("Kewarganegaraan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KEWARGANEGARAAN");

                    b.Property<string>("KotaId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KOTA_ID");

                    b.Property<string>("NamaCetakan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("NAMA_CETAKAN");

                    b.Property<string>("NamaLengkap")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAMA_LENGKAP");

                    b.Property<string>("NamaSesuaiId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAMA_SESUAI_ID");

                    b.Property<string>("Negara")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NEGARA");

                    b.Property<string>("NoHp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NO_HP");

                    b.Property<string>("NoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NO_ID");

                    b.Property<string>("Npwp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NPWP");

                    b.Property<string>("PropinsiId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PROPINSI_ID");

                    b.Property<string>("StatusPerkawinan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATUS_PERKAWINAN");

                    b.Property<string>("TanggalLahir")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TANGGAL_LAHIR");

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TEMPAT_LAHIR");

                    b.ToTable("abcs_m_cfmast");
                });
#pragma warning restore 612, 618
        }
    }
}
