// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sa_inquiry.Data;

#nullable disable

namespace sa_inquiry.Migrations
{
    [DbContext(typeof(SaInquiryContext))]
    partial class SaInquiryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sa_inquiry.Models.Entity.ABCS_M_DDMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER")
                        .HasColumnOrder(1);

                    b.Property<string>("AccountNumberHold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBERHOLD")
                        .HasColumnOrder(49);

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE")
                        .HasColumnOrder(2);

                    b.Property<string>("Accrue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCRUE")
                        .HasColumnOrder(19);

                    b.Property<string>("AccrueTemp")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ACCRUETEMP")
                        .HasColumnOrder(41);

                    b.Property<string>("Addr")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ADDR")
                        .HasColumnOrder(33);

                    b.Property<string>("ArrCbalTemp")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ARRCBALTEMP")
                        .HasColumnOrder(43);

                    b.Property<string>("ArrRateTemp")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ARRRATETEMP")
                        .HasColumnOrder(44);

                    b.Property<string>("BirthDate")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("BIRTHDATE")
                        .HasColumnOrder(54);

                    b.Property<string>("BranchOld")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRANCHOLD")
                        .HasColumnOrder(52);

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL")
                        .HasColumnOrder(4);

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM")
                        .HasColumnOrder(3);

                    b.Property<string>("CifNumOld")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CIFNUMOLD")
                        .HasColumnOrder(51);

                    b.Property<string>("CifRelation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CIFRELATION")
                        .HasColumnOrder(40);

                    b.Property<string>("ClosingDate6")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLOSINGDATE6")
                        .HasColumnOrder(45);

                    b.Property<string>("ClosingDate7")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLOSINGDATE7")
                        .HasColumnOrder(46);

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY")
                        .HasColumnOrder(8);

                    b.Property<string>("DateLastIntPaid6")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DATELASTINTPAID6")
                        .HasColumnOrder(23);

                    b.Property<string>("DateLastIntPaid7")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DATELASTINTPAID7")
                        .HasColumnOrder(24);

                    b.Property<string>("Dtlm6")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DTLM6")
                        .HasColumnOrder(26);

                    b.Property<string>("Dtlm7")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DTLM7")
                        .HasColumnOrder(27);

                    b.Property<string>("ExpDate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EXPDATE")
                        .HasColumnOrder(48);

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GROUPCODE")
                        .HasColumnOrder(25);

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD")
                        .HasColumnOrder(5);

                    b.Property<string>("IntCycle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("INTCYCLE")
                        .HasColumnOrder(13);

                    b.Property<string>("IntType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("INTTYPE")
                        .HasColumnOrder(47);

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JENIS_KELAMIN")
                        .HasColumnOrder(55);

                    b.Property<string>("KodeFo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KODEFO")
                        .HasColumnOrder(38);

                    b.Property<string>("LastTranDate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LASTTRANDATE")
                        .HasColumnOrder(21);

                    b.Property<string>("LastTranDate7")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LASTTRANDATE7")
                        .HasColumnOrder(22);

                    b.Property<string>("MinimumBalanceDays")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MINIMUMBALANCEDAYS")
                        .HasColumnOrder(35);

                    b.Property<string>("Nik")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NIK")
                        .HasColumnOrder(53);

                    b.Property<string>("OdAccrue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ODACCRUE")
                        .HasColumnOrder(20);

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6")
                        .HasColumnOrder(15);

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7")
                        .HasColumnOrder(16);

                    b.Property<string>("PVAR")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PVAR")
                        .HasColumnOrder(11);

                    b.Property<string>("ProductCodeOld")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PRODUCTCODEOLD")
                        .HasColumnOrder(50);

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE")
                        .HasColumnOrder(7);

                    b.Property<string>("PvarCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PVARCODE")
                        .HasColumnOrder(12);

                    b.Property<string>("QQName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("QQNAME")
                        .HasColumnOrder(37);

                    b.Property<string>("Rate")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("RATE")
                        .HasColumnOrder(10);

                    b.Property<string>("RateTemp")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("RATETEMP")
                        .HasColumnOrder(42);

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RELATION")
                        .HasColumnOrder(39);

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME")
                        .HasColumnOrder(6);

                    b.Property<string>("Sidlm")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SIDLM")
                        .HasColumnOrder(30);

                    b.Property<string>("Skb")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SKB")
                        .HasColumnOrder(32);

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(9);

                    b.Property<string>("SvcCycle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SVCCYCLE")
                        .HasColumnOrder(14);

                    b.Property<string>("Tax")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("TAX")
                        .HasColumnOrder(31);

                    b.Property<string>("TaxAccrue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TAXACCRUE")
                        .HasColumnOrder(34);

                    b.Property<string>("Tmlm")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TMLM")
                        .HasColumnOrder(28);

                    b.Property<string>("Uid")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UID")
                        .HasColumnOrder(17);

                    b.Property<string>("Uidlm")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UIDLM")
                        .HasColumnOrder(29);

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL")
                        .HasColumnOrder(18);

                    b.Property<string>("ZeroBalanceDays")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ZEROBALANCEDAYS")
                        .HasColumnOrder(36);

                    b.ToTable("ABCS_M_DDMAST");
                });
#pragma warning restore 612, 618
        }
    }
}
