// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using accountnumber_inquiry.Data;

#nullable disable

namespace accountnumber_inquiry.Migrations
{
    [DbContext(typeof(AccountNumberInquiryContext))]
    [Migration("20230731082630_menambah_tabel")]
    partial class menambah_tabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_CDMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_cdmast");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_CDMEMO", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_cdmemo");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_DDMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_ddmast");
                });

            modelBuilder.Entity("Inquiry.Models.Entity.ABCS_M_DDMEMO", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("abcs_m_ddmemo");
                });

            modelBuilder.Entity("accountnumber_inquiry.Models.Entity.ABCS_M_GLMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("AmountEquivalence")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AMOUNTEQUIVALENCE");

                    b.Property<string>("BookingRate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BOOKINGRATE");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRANCH");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("Center")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CENTER");

                    b.Property<string>("CifRelation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CIFRELATION");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("QqName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("QQNAME");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RELATION");

                    b.Property<string>("ShortName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("YAmountEquivalence")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YAMOUNTEQUIVALENCE");

                    b.Property<string>("YBookingRate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBOOKINGRATE");

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL");

                    b.ToTable("ABCS_M_GLMAST");
                });

            modelBuilder.Entity("accountnumber_inquiry.Models.Entity.ABCS_M_GLMEMO", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER")
                        .HasColumnOrder(2);

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTTYPE")
                        .HasColumnOrder(3);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRANCH")
                        .HasColumnOrder(1);

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL")
                        .HasColumnOrder(5);

                    b.Property<string>("Center")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CENTER")
                        .HasColumnOrder(8);

                    b.Property<string>("CifRelation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CIFRELATION")
                        .HasColumnOrder(13);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CURRENCY")
                        .HasColumnOrder(4);

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GROUPCODE")
                        .HasColumnOrder(9);

                    b.Property<string>("QqName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("QQNAME")
                        .HasColumnOrder(11);

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RELATION")
                        .HasColumnOrder(12);

                    b.Property<string>("ShortName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("SHORTNAME")
                        .HasColumnOrder(7);

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(6);

                    b.Property<string>("Ybal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("YBAL")
                        .HasColumnOrder(10);

                    b.ToTable("ABCS_M_GLMEMO");
                });

            modelBuilder.Entity("accountnumber_inquiry.Models.Entity.ABCS_M_LNMAST", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.ToTable("ABCS_M_LNMAST");
                });

            modelBuilder.Entity("accountnumber_inquiry.Models.Entity.ABCS_M_LNMEMO", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTNUMBER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("Cbal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CBAL");

                    b.Property<string>("CifNum")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CIFNUM");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("Hold")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HOLD");

                    b.Property<string>("OpenDat6")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("OPENDAT6");

                    b.Property<string>("OpenDat7")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OPENDAT7");

                    b.Property<string>("ProductType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PRODUCTTYPE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SHORTNAME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.ToTable("ABCS_M_LNMEMO");
                });
#pragma warning restore 612, 618
        }
    }
}
